### ISSUE TITLE
FollowEvent?

### ISSUE THREAD

**Issue by leeoniya** [gr2m/helpdesk#63] opened 2023-09-11 02:49 UTC
Hi @gr2m!

I'm working on a little something to mitigate the recent Github home feed fiasco [1], for myself and possibly for many many others. So far, I've found the REST API to be mostly sufficient to re-create the [old feed](https://github.com/dashboard-feed) (and even improve on it in numerous ways), with one exception: the absence of **Follow** events -- both, new own followers and who your followees are newly following. I don't see anything like this documented here: https://docs.github.com/en/rest/overview/github-event-types?apiVersion=2022-11-28

I'm really hoping I don't have to work around the lack of this by continuously polling and diffing from these other APIs [2] and chewing through the 5,000 daily req token limit.

Would it be possible to add something like this?

Also, only having ~250 most recent events `https://api.github.com/users/${user}/received_events?per_page=${perPage}&page=${page}` is kind of a bummer, but i can work around it with polling + localStorage cache. trying to grab more than the limit i get this error, but i don't see the Link header in the response that error message is referring to:

```json
{
  "message": "In order to keep the API fast for everyone, pagination is limited for this resource. Check the rel=last link relation in the Link response header to see how far back you can traverse.",
  "documentation_url": "https://docs.github.com/v3/#pagination"
}
```

any advice would be greatly appreciated :)
thanks!

[1] https://github.com/orgs/community/discussions/categories/feed
[2] https://docs.github.com/en/rest/users/followers?apiVersion=2022-11-28

**Comment by gr2m** [comment] 2023-09-11 18:38
> Would it be possible to add something like this?

I can't really help with adding new APIs, I can only help utilizing the existing ones. It does seem like there are no events for follows unfortunately. You can contact support and request it. There is also an official forum for all kind of API/Webhook questions: https://github.com/orgs/community/discussions/categories/api-and-webhooks

**Comment by leeoniya** [comment] 2023-09-11 18:56
i've provided feedback maybe 5 times over the past 10 years using a variety of official channels. each time i get the same reply as the one below, then radio silence and nothing happens.

https://github.com/orgs/community/discussions/57326#discussioncomment-6187314

the story is always the same. carbon copy, template response.

https://github.com/orgs/community/discussions/64982

i dont expect anything meaningful to happen there either. it's truly a maddening experince when a company says they value feedback, and encourage it. and then simply ignore it, or do exactly the opposite (as the recent feed changes show).

im really tired of talking through github's useless devrel. i'd rather reach out through engineers, which is why i'm here.

**Comment by gr2m** [comment] 2023-09-11 19:57
I understand your frustration, I've been there most of my career. But even now within GitHub, there is only so much I can do. I'm not working in the API space, I'm not even working on Octokit anymore. But I can confirm that the requests like yours are being tracked and prioritized.

I'll close the issue because there is nothing else I can do to help you, I'm afraid.

**Closed as completed by gr2m** 2023-09-11 19:57 UTC

**Comment by leeoniya** [comment] 2023-09-11 20:03
> But I can confirm that the requests like yours are being tracked and prioritized.

empirically, i've seen no evidence of this :(

**Comment by justinclift** [comment] 2023-09-12 03:23
Yeah.  GitHub's reputation is pretty lousy for stuff like this. :frowning:
